name       : perl-sub-name
version    : '0.27'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/Sub-Name-0.27.tar.gz : ecf36fba1c47ca93e1daa394968ed39c4186867459d9cd173c421e2b972043e8
homepage   : https://metacpan.org/pod/Sub::Name
license    : Artistic-2.0
component  : programming.perl
summary    : |
    (Re)name a sub
description: |
    (Re)name a sub
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
