name       : perl-sub-name
version    : '0.26'
release    : 6
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/Sub-Name-0.26.tar.gz : 2d2f2d697d516c89547e7c4307f1e79441641cae2c7395e7319b306d390df105
license    : Artistic-2.0
component  : programming.perl
summary    : |
    (Re)name a sub
description: |
    (Re)name a sub
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
