name       : perl-sub-name
version    : 0.21
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/E/ET/ETHER/Sub-Name-0.21.tar.gz : bd32e9dee07047c10ae474c9f17d458b6e9885a6db69474c7a494ccc34c27117
license    : Artistic-2.0
component  : programming.perl
summary    : |
    (Re)name a sub
description: |
    (Re)name a sub
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
